export const categoryPT: Record<string, string> = {
  developer_tools: "Ferramentas de desenvolvimento",
  backend: "Backend",
  hosting: "Hospedagem",
  tools: "Ferramentas",
  entertainment: "Entretenimento",
  social: "Social",
  media: "Mídia",
  search: "Busca",
  forms: "Formulários",
  email: "E-mail",
  education: "Educação",
  open_data: "Dados abertos",
  text: "Texto",
  machine_learning: "Machine Learning",
  analytics: "Análise de dados",
  financial: "Financeiro",
  payment: "Pagamentos",
  ecommerce: "E-commerce",
  location: "Localização",
};